using VeilleConcurrentielle.Aggregator.WebApp.Data.Entities;
using VeilleConcurrentielle.Infrastructure.Data;

namespace VeilleConcurrentielle.Aggregator.WebApp.Data.Repositories
{
    public class StrategyRepository : RepositoryBase<StrategyEntity>, IStrategyRepository
    {
        public StrategyRepository(AggregatorDbContext dbContext) : base(dbContext)
        {
        }

        public override void ComputeNewIdBeforeInsert(StrategyEntity entity)
        {
            // Id is not autogenerated
        }
    }
}
